run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  max-same-issues: 0

linters:
  disable-all: true
  enable:
#  - asciicheck
  - bodyclose
  - unused
  - depguard
  - dogsled
  - dupl
  - errcheck
#  - exhaustive
#  - exportloopref
#  - funlen
#  - gci
#  - gochecknoglobals
#  - gochecknoinits
#  - gocognit
#  - goconst
  - gocritic
  - gocyclo
#  - godot
  - godox
#  - goerr113
  - gofmt
#  - gofumpt
#  - goheader
  - goimports
  - revive
#  - gomnd
#  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
#  - lll
  - misspell
  - nakedret
#  - nestif
#  - nlreturn
#  - noctx
#  - nolintlint
  - prealloc
  - rowserrcheck
  - copyloopvar
#  - sqlclosecheck
  - staticcheck
  - stylecheck
#  - testpackage
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
#  - wsl
